# Generated by Django 5.1.7 on 2025-04-18 15:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=60, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Proyecto')),
                ('description', models.TextField(null=True, verbose_name='Descripción del Proyecto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('finished_at', models.DateTimeField(null=True, verbose_name='Fecha de Finalización')),
                ('end_date', models.DateField(null=True, verbose_name='Fecha de Fin')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('completed', 'Completado'), ('stopped', 'Detenido'), ('planning', 'En planificación')], max_length=20, verbose_name='Estado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
