# Generated by Django 5.1.7 on 2025-04-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0002_project_updated_at_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Proyecto'),
        ),
    ]
