# Generated by Django 5.1.7 on 2025-04-25 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_projects', '0004_project_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=60, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Tarea')),
                ('description', models.TextField(null=True, verbose_name='Descripción de la Tarea')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=20, verbose_name='Prioridad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('finished_at', models.DateTimeField(null=True, verbose_name='Fecha de Finalización')),
                ('end_date', models.DateField(null=True, verbose_name='Fecha de Fin')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app_projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
    ]
