# Generated by Django 5.1.7 on 2025-04-25 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0004_project_favorite'),
        ('app_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tasks',
            unique_together={('name', 'project')},
        ),
    ]
